version: '2.2'
services:
  esmain:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: esmain
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/esmain/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    scale: 2
    depends_on:
      - esmain
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=esmain"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/es/data
    networks:
      - esnet

  kibana:
    image: whoisb/eng_kibana
    ports:
      - 5601:5601
    stdin_open: true
    tty: true
    entrypoint: 
      - /bin/bash
    networks:
      - esnet

  fb:
      image: whoisb/fb
      stdin_open: true
      tty: true
      networks:
        - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:

